export enum MainCategory {
    ENTERTAINMENT = 'ENTERTAINMENT',
    TECHNOLOGY = 'TECHNOLOGY',
    SPORTS = 'SPORTS',
    LIFESTYLE = 'LIFESTYLE',
    SEXUALITY = 'SEXUALITY',
    GASTRONOMY = 'GASTRONOMY',
    HOBBIES = 'HOBBIES',
    FINANCE = 'FINANCE',
    SCIENCE = 'SCIENCE',
    CARS_AND_MOTORCYCLES = 'CARS_AND_MOTORCYCLES',
    EDUCATION_AND_CAREER = 'EDUCATION_AND_CAREER',
    OTHER = 'OTHER'
}
