export enum SubCategory {
    // Entertainment
    MOVIES_AND_SERIES = 'MOVIES_AND_SERIES',
    MUSIC = 'MUSIC',
    VIDEO_GAMES = 'VIDEO_GAMES',
    BOOKS_AND_COMICS = 'BOOKS_AND_COMICS',
    THEATER_AND_PERFORMING_ARTS = 'THEATER_AND_PERFORMING_ARTS',
    ENTERTAINMENT = 'OTHER_ENTERTAINMENT',

    // Technology
    PROGRAMMING = 'PROGRAMMING',
    MOBILE_APPS = 'MOBILE_APPS',
    HARDWARE = 'HARDWARE',
    CYBER_SECURITY = 'CYBER_SECURITY',
    ARTIFICIAL_INTELLIGENCE = 'ARTIFICIAL_INTELLIGENCE',

    // Sports
    FOOTBALL = 'FOOTBALL',
    BASKETBALL = 'BASKETBALL',
    EXTREME_SPORTS = 'EXTREME_SPORTS',
    ESPORTS = 'ESPORTS',
    FITNESS_AND_BODYBUILDING = 'FITNESS_AND_BODYBUILDING',

    // Lifestyle
    HEALTHY_EATING = 'HEALTHY_EATING',
    TRAVEL_AND_ADVENTURE = 'TRAVEL_AND_ADVENTURE',
    FASHION_AND_BEAUTY = 'FASHION_AND_BEAUTY',
    HOME_GARDENING = 'HOME_GARDENING',
    RELATIONSHIPS_AND_FAMILY = 'RELATIONSHIPS_AND_FAMILY',

    // Sexuality
    SEXUAL_HEALTH = 'SEXUAL_HEALTH',
    RELATIONSHIPS_AND_DATING = 'RELATIONSHIPS_AND_DATING',
    SEXUAL_ORIENTATION = 'SEXUAL_ORIENTATION',
    INTIMACY_AND_COMMUNICATION = 'INTIMACY_AND_COMMUNICATION',
    SOCIAL_AND_CULTURAL_ISSUES = 'SOCIAL_AND_CULTURAL_ISSUES',

    // Gastronomy
    FOOD_AND_RECIPES = 'FOOD_AND_RECIPES',
    RESTAURANTS_AND_CAFES = 'RESTAURANTS_AND_CAFES',
    WINES_AND_BEERS = 'WINES_AND_BEERS',
    VEGETARIAN_AND_VEGAN_FOOD = 'VEGETARIAN_AND_VEGAN_FOOD',
    WORLDWIDE_CUISINES = 'WORLDWIDE_CUISINES',

    // Hobbies
    CRAFTING = 'CRAFTING',
    MODEL_BUILDING = 'MODEL_BUILDING',
    PHOTOGRAPHY = 'PHOTOGRAPHY',
    FURNITURE_RESTORATION = 'FURNITURE_RESTORATION',
    FISHING = 'FISHING',

    // Finance
    INVESTMENTS = 'INVESTMENTS',
    CRYPTOCURRENCIES = 'CRYPTOCURRENCIES',
    PERSONAL_FINANCE = 'PERSONAL_FINANCE',
    REAL_ESTATE_MARKET = 'REAL_ESTATE_MARKET',
    BUSINESS_TRENDS = 'BUSINESS_TRENDS',

    // Science
    SPACE_EXPLORATION = 'SPACE_EXPLORATION',
    PHYSICS = 'PHYSICS',
    BIOLOGY = 'BIOLOGY',
    CHEMISTRY = 'CHEMISTRY',
    SCIENCE_NEWS = 'SCIENCE_NEWS',

    // Cars and Motorcycles
    CAR_RACING = 'CAR_RACING',
    ELECTRIC_VEHICLES = 'ELECTRIC_VEHICLES',
    CLASSIC_CARS = 'CLASSIC_CARS',
    MOTORBIKES = 'MOTORBIKES',
    VEHICLE_MAINTENANCE_AND_TUNING = 'VEHICLE_MAINTENANCE_AND_TUNING',

    // Education and Career
    LANGUAGE_LEARNING = 'LANGUAGE_LEARNING',
    CAREER_ADVICE = 'CAREER_ADVICE',
    ONLINE_COURSES = 'ONLINE_COURSES',
    HIGHER_EDUCATION = 'HIGHER_EDUCATION',
    CAREER_GUIDANCE = 'CAREER_GUIDANCE',

    // Other
    OTHER = 'OTHER'
}
