spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/forum
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
application:
  security:
    jwt:
      secret-key: 97f8d91e1168697e9abbf487e06b99ebd9f7219514d7938cfa6ba9dd8856f2e7
      expiration: 86400000
  file:
    upload:
      photos-output-path: ./uploads