package com.app.forum.enums;

public enum SubCategoryType {
	
    // Entertainment
    MOVIES_AND_SERIES,
    MUSIC,
    VIDEO_GAMES,
    BOOKS_AND_COMICS,
    THEATER_AND_PERFORMING_ARTS,

    // Technology
    PROGRAMMING,
    MOBILE_APPS,
    HARDWARE,
    CYBER_SECURITY,
    ARTIFICIAL_INTELLIGENCE,

    // Sports
    FOOTBALL,
    BASKETBALL,
    EXTREME_SPORTS,
    ESPORTS,
    FITNESS_AND_BODYBUILDING,

    // Lifestyle
    HEALTHY_EATING,
    TRAVEL_AND_ADVENTURE,
    FASHION_AND_BEAUTY,
    HOME_GARDENING,
    RELATIONSHIPS_AND_FAMILY,

    // Sexuality
    SEXUAL_HEALTH,
    RELATIONSHIPS_AND_DATING,
    SEXUAL_ORIENTATION,
    INTIMACY_AND_COMMUNICATION,
    SOCIAL_AND_CULTURAL_ISSUES,

    // Gastronomy
    FOOD_AND_RECIPES,
    RESTAURANTS_AND_CAFES,
    WINES_AND_BEERS,
    VEGETARIAN_AND_VEGAN_FOOD,
    WORLDWIDE_CUISINES,

    // Hobbies
    CRAFTING,
    MODEL_BUILDING,
    PHOTOGRAPHY,
    FURNITURE_RESTORATION,
    FISHING,

    // Finance
    INVESTMENTS,
    CRYPTOCURRENCIES,
    PERSONAL_FINANCE,
    REAL_ESTATE_MARKET,
    BUSINESS_TRENDS,

    // Science
    SPACE_EXPLORATION,
    PHYSICS,
    BIOLOGY,
    CHEMISTRY,
    SCIENCE_NEWS,

    // Cars and Motorcycles
    CAR_RACING,
    ELECTRIC_VEHICLES,
    CLASSIC_CARS,
    MOTORBIKES,
    VEHICLE_MAINTENANCE_AND_TUNING,

    // Education and Career
    LANGUAGE_LEARNING,
    CAREER_ADVICE,
    ONLINE_COURSES,
    HIGHER_EDUCATION,
    CAREER_GUIDANCE,

    // Other
    OTHER;
}
